In [1]:
a=6
b=7
c=a+b
print(c)


13


In [2]:
import numpy as np


In [3]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3])
print(a*2)
print(b+2)

[ 2  4  6  8 10]
[3 4 5]


In [9]:
a=np.char.array(['apple '])
print(a)


['apple']


In [22]:
a=np.array([10,100,1,2,3])
b=sorted(a)
print(b)
np.append(a,[101,10001])

[1, 2, 3, 10, 100]


array([   10,   100,     1,     2,     3,   101, 10001])

In [33]:
large_sequence = np.arange(1000000)
square_matrix=np.reshape(large_sequence,(1000,1000))


In [34]:
print(square_matrix)

[[     0      1      2 ...    997    998    999]
 [  1000   1001   1002 ...   1997   1998   1999]
 [  2000   2001   2002 ...   2997   2998   2999]
 ...
 [997000 997001 997002 ... 997997 997998 997999]
 [998000 998001 998002 ... 998997 998998 998999]
 [999000 999001 999002 ... 999997 999998 999999]]


In [41]:
p1=np.min(large_sequence)
p2=np.max(large_sequence)
p4=np.mean(large_sequence)
print(p1,p2,p4)

0 999999 499999.5


In [ ]:

import pandas as pd

